In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import seaborn as sns

In [4]:
dataset=pd.read_csv("C:\\Users\\Student\\Downloads\\advertising.csv")

In [5]:
dataset.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [6]:
x=dataset[['TV', 'Radio', 'Newspaper']]
y=dataset['Sales']

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=100)

In [10]:
mlr=LinearRegression()
mlr.fit(X_train, Y_train)

LinearRegression()

In [18]:
print(f'intercept: {mlr.intercept_}')

intercept: 4.334595861728431

In [19]:
print(f'coefficient: {mlr.coef_}')

coefficient: [0.05382911 0.11001224 0.00628995]

In [21]:
print('coefficient')
list(zip(x, mlr.coef_))

coefficient

[('TV', 0.053829108667250075),
 ('Radio', 0.11001224388558062),
 ('Newspaper', 0.0062899501461303525)]

In [23]:
y_pread_mlr=mlr.predict(X_test)

In [24]:
Y_pred_test = mlr.predict(X_test)
Y_pred_train = mlr.predict(X_train)
print('Prediction for test set: {}'.format(Y_pred_test))

Prediction for test set: [ 9.35221067 20.96344625 16.48851064 20.10971005 21.67148354 16.16054424
 13.5618056  15.39338129 20.81980757 21.00537077 12.29451311 20.70848608
  8.17367308 16.82471534 10.48954832  9.99530649 16.34698901 14.5758119
 17.23065133 12.56890735 18.55715915 12.12402775 20.43312609 17.78017811
 16.73623408 21.60387629 20.13532087 10.82559967 19.12782848 14.84537816
 13.13597397  9.07757918 12.07834143 16.62824427  8.41792841 14.0456697
  9.92050209 14.26101605 16.76262961 17.17185467 18.88797595 15.50165469
 15.78688377 16.86266686 13.03405813 10.47673934 10.6141644  20.85264977
 10.1517568   6.88471443 17.88702583 18.16013938 12.55907083 16.28189561
 18.98024679 11.33714913  5.91026916 10.06159509 17.62383031 13.19628335]

In [29]:
mlr_diff=pd.DataFrame({'actual value': Y_test, 'predicted value': y_pread_mlr})
mlr_diff.head(20)

     actual value  predicted value
126           6.6         9.352211
104          20.7        20.963446
99           17.2        16.488511
92           19.4        20.109710
111          21.8        21.671484
167          17.2        16.160544
116          12.2        13.561806
96           16.7        15.393381
52           22.6        20.819808
69           22.3        21.005371
164          11.9        12.294513
124          19.7        20.708486
182           8.7         8.173673
154          20.6        16.824715
125          10.6        10.489548
196          14.0         9.995306
194          17.3        16.346989
177          16.7        14.575812
163          18.0        17.230651
31           11.9        12.568907